dist: xenial
language: cpp
compiler: clang

before_install:
  - sudo apt-get install libjemalloc-dev libpcre3-dev

install: autoreconf -if

script: ./configure CXXFLAGS='-stdlib=libc++' && make -j4 && make test
