dist: xenial
language: cpp
compiler: gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install libjemalloc-dev libpcre3-dev

install: autoreconf -if

script: ./configure && make -j4 && make test
